language: php
branches:
  only:
    - master
before_script:
  - git clone https://github.com/NHNajibullah/simple-ci.git
  - cd simple-ci
  - sudo apt update
  - sudo apt -qq install git-ftp

script:
  - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://$FTP_HOST

after_script:
  - echo "Build Berhasil"