language: php

branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install git-ftp

before_script:
  - git clone https://github.com/NHNajibullah/simple-ci.git
  - cd simple-ci

script:
  - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://$FTP_HOST
