language: php
php:
  - '5.6'
  - '7.1'
  - hhvm # on Trusty only
  - nightly
deploy:
  provider: ftp
  host: ftp://$FTP_HOST
  user: $FTP_USERNAME
  password: $FTP_PASSWORD
  skip_cleanup: true
  on:
    branch: master
